apiVersion: v1
kind: Namespace
metadata:
  name: go-test-coverage-demo

---

apiVersion: v1
kind: Service
metadata:
  namespace: go-test-coverage-demo
  name: test-exec
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: test-exec

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-test-coverage-demo
  name: test-exec
  labels:
    app: test-exec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-exec
  template:
    metadata:
      labels:
        app: test-exec
    spec:
      containers:
        - image: go-test-coverage-demo/test-exec
          imagePullPolicy: Never
          name: external-test
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: coverage
              mountPath: /coverage
      volumes:
        - name: coverage
          hostPath:
            path: /tmp/coverage

---

apiVersion: v1
kind: Service
metadata:
  namespace: go-test-coverage-demo
  name: coverage-viewer
  labels:
    app: coverage-viewer
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: coverage-viewer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-test-coverage-demo
  name: coverage-viewer
  labels:
    app: coverage-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coverage-viewer
  template:
    metadata:
      labels:
        app: coverage-viewer
    spec:
      containers:
        - name: shaas
          image: heroku/shaas
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: coverage
              mountPath: /coverage
      volumes:
        - name: coverage
          hostPath:
            path: /tmp/coverage
