apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-test
  name: external-test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: external-test
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: external-test
  name: external-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: external-test
  template:
    metadata:
      labels:
        run: external-test
    spec:
      containers:
        - image: external-test
          imagePullPolicy: Never
          name: external-test
          ports:
            - name: http
              containerPort: 8080

